### ISSUE TITLE
What is the role of the WhiteMask?

### ISSUE THREAD

**Issue by ratishphilip** [JustinXinLiu/EffectsAndAnimationsWinComposition#1]
in your example, in MainPage.xaml, what is the role of 
<Rectangle x:Name="WhiteMask" Fill="White" />

if I remove it, the image is no longer blurred. How does it affect the blurring?

**Comment by JustinXinLiu** [comment]
of?

**Comment by ratishphilip** [comment]
the blurring of the background image (Image2).
If I remove the WhiteMask rectangle, the Image2 does not appear blurred. But when I put the WhiteMask Rectangle behind the CanvasControl, the background image appears blurred.

I just wish to know how the blurring is happening.

**Comment by JustinXinLiu** [comment]
After applying the `GaussianBlurEffect`, the image is turned blurred. Then you need to tint it with a color. In this case I am using _white_ for the **frosted glass** feel.

**Comment by ratishphilip** [comment]
thanks for the clarification.
